# Generated by Django 5.1.3 on 2024-11-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0002_kullanici_is_yetkili'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='yillik_izin_gunu',
        ),
    ]
