# Generated by Django 5.1.3 on 2024-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0003_remove_kullanici_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='annual_leave_balance',
            field=models.IntegerField(default=15),
        ),
    ]
