# Generated by Django 5.1.3 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saat', '0002_alter_giriscikiskayit_giris_saati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giriscikiskayit',
            name='giris_saati',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
